insert into ship_type(id, name)	values (-1, "Battleship"			)
insert into ship_type(id, name)	values (-2, "Battle Cruiser"		)
insert into ship_type(id, name)	values (-3, "Armoured Cruiser"	)
insert into ship_type(id, name)	values (-4, "Heavy Cruiser"		)
insert into ship_type(id, name)	values (-5, "Light Cruiser"		)
insert into ship_type(id, name)	values (-6, "Destroyer"			)
insert into ship_type(id, name)	values (-7, "Torpedo Boat"		)

insert into nation(id, name)	values (-1, "USA")
insert into nation(id, name)	values (-2, "UK")
insert into nation(id, name)	values (-3, "France")
insert into nation(id, name)	values (-4, "Japan")
insert into nation(id, name)	values (-5, "Germany")
insert into nation(id, name)	values (-6, "Italy")

insert into gun(id, nation_id, caliber, barrel) values(-1,-2, 120, 45 )
insert into gun(id, nation_id, caliber, barrel) values(-2,-1, 127, 38 )

insert into ship(id, nation_id, name, laid_down_date, ship_class, ship_type_id) values(-1,-1,	"Iowa", 			DATE '1938-11-22', "Iowa", -1)
insert into ship(id, nation_id, name, laid_down_date, ship_class, ship_type_id) values(-2,-1,	"Missouri",		DATE '1939-11-22', "Iowa", -1)
insert into ship(id, nation_id, name, laid_down_date, ship_class, ship_type_id) values(-3,-1,	"New Jersey", 	DATE '1939-05-22', "Iowa", -1)